name: fluent2ui
description: A robust Fluent2 Material-based design system for seamless and intuitive user experiences.
version: 9.0.1
repository: https://github.com/grbtec/fluent2ui
publish_to: https://dart.indicacode.com

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.223
  custom_sliding_segmented_control: ^1.7.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true
